import 'react-toastify/dist/ReactToastify.css';
import '../styles/globals.css';

import moment from 'moment';
import { type Metadata } from 'next';
import { Inter } from 'next/font/google';
import Providers from './providers';
moment.locale('pt-br');

const inter = Inter({ subsets: ['latin'] });
export const metadata: Metadata = {
  title: 'FastCurriculum - Encurtador de URL',
  description: 'Generated by VoteMe - Encurtador de URL',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html className="h-full bg-slate-100" lang="pt-br">
      <body
        className={`${inter.className} h-full justify-center items-center w-auto`}
      >
        <Providers>{children}</Providers>
      </body>
    </html>
  );
}
